"""init migrate

Revision ID: 28551ae035a
Revises: 4fe83237c93
Create Date: 2015-11-12 22:14:33.068485

"""

# revision identifiers, used by Alembic.
revision = '28551ae035a'
down_revision = '4fe83237c93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bbsusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Uname', sa.String(length=64), nullable=False),
    sa.Column('Upwdhash', sa.String(length=16), nullable=False),
    sa.Column('Uemail', sa.String(length=64), nullable=False),
    sa.Column('Confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('localtion', sa.String(length=64), nullable=True),
    sa.Column('aboutme', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('Role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Uemail')
    )
    op.create_index(op.f('ix_bbsusers_Uname'), 'bbsusers', ['Uname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bbsusers_Uname'), table_name='bbsusers')
    op.drop_table('bbsusers')
    op.drop_table('roles')
    ### end Alembic commands ###
